mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 开启字段下划线映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志
  global-config:
    db-config:
      table-underline: true             # 表名下划线格式
      # 如果有表前缀可配置
      # table-prefix: t_
  mapper-locations: classpath*:mappers/*.xml  # 指定mapper XML文件位置
  type-aliases-package: com.rural.platform.entity  # 指定实体类包路径

weather:
  api:
    key: 68db13a6d081478eb6615c91a3074c0e  # 替换为你的和风天气 API key
    version: "7"
    base-url: "https://api.qweather.com"
