CREATE TABLE `cultural_activity` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `title` varchar(100) NOT NULL COMMENT '活动标题',
    `description` text COMMENT '活动描述',
    `content` text COMMENT '活动内容',
    `location` varchar(200) NOT NULL COMMENT '活动地点',
    `start_time` datetime NOT NULL COMMENT '开始时间',
    `end_time` datetime NOT NULL COMMENT '结束时间',
    `organizer` varchar(100) NOT NULL COMMENT '主办方',
    `contact` varchar(50) COMMENT '联系人',
    `phone` varchar(20) COMMENT '联系电话',
    `max_participants` int DEFAULT NULL COMMENT '最大参与人数',
    `current_participants` int DEFAULT 0 COMMENT '当前参与人数',
    `image_url` varchar(255) DEFAULT NULL COMMENT '活动图片URL',
    `status` int NOT NULL DEFAULT 1 COMMENT '活动状态：0-已删除，1-正常',
    `category` varchar(50) DEFAULT NULL COMMENT '活动类别',
    `author` varchar(50) DEFAULT NULL COMMENT '作者',
    `view_count` int DEFAULT 0 COMMENT '浏览次数',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_status` (`status`),
    KEY `idx_category` (`category`),
    KEY `idx_start_time` (`start_time`),
    KEY `idx_end_time` (`end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文化活动表'; 